"""Obsidian-native cockpit — Markdown/Dataview review surfaces.

Generates review dashboards using canonical vault files.  Never overwrites
owner-edited files without an exact reviewed plan with expected-hash protection.
"""

from __future__ import annotations

from pathlib import Path

from .storage import atomic_write_text
from .vault import is_initialized


class CockpitError(RuntimeError):
    """Raised when cockpit operations fail."""


COCKPIT_HOME = """# Constellation Cockpit

> Auto-generated review dashboard. Manual edits preserved across regens.

## Candidate Queue

```dataview
TABLE file.cday AS "Staged", type AS "Type", status AS "Status"
FROM ".constellation/candidates"
SORT file.cday DESC
```

## Entity Timeline

```dataview
TABLE created_at AS "Created", sensitivity AS "Sensitivity"
FROM "entities"
SORT created_at DESC
LIMIT 20
```

## Source Evidence

```dataview
TABLE media_type AS "Format", sensitivity AS "Sensitivity"
FROM "source-items"
SORT created_at DESC
LIMIT 20
```

## Opportunities

```dataview
TABLE stage AS "Stage", probability AS "Prob", next_action AS "Next Action"
FROM "opportunities"
SORT created_at DESC
```

## Classifications

```dataview
TABLE category AS "Category", entity_id AS "Entity", confidence AS "Confidence"
FROM "classifications"
SORT created_at DESC
```

## Analyses

```dataview
TABLE framework AS "Framework", entity_id AS "Entity", confidence AS "Confidence"
FROM "analyses"
SORT created_at DESC
```

## Watchlists & Observations

```dataview
TABLE schedule AS "Schedule", sources AS "Sources"
FROM "watchlists"
SORT created_at DESC
```

## Warnings

- Degraded services: check `constellation health` output
- Stale indexes: run `constellation index` if search results seem incomplete
- Unreviewed candidates: see Candidate Queue above

_Generated by `constellation cockpit apply`_
"""


def cockpit_plan(vault: Path | str) -> dict[str, object]:
    """Plan cockpit generation — reports what would be written."""
    vault = Path(vault).absolute()
    if not is_initialized(vault):
        raise CockpitError("vault is not initialized")

    target = vault / "HOME.md"
    return {
        "status": "plan_ready",
        "target": "HOME.md",
        "exists": target.is_file(),
        "action": "create" if not target.is_file() else "update",
    }


def cockpit_apply(vault: Path | str, *, dry_run: bool = False) -> dict[str, object]:
    """Generate or update the cockpit HOME.md dashboard.

    Always overwrites — cockpit is auto-generated, not user-edited.
    """
    vault = Path(vault).absolute()
    if not is_initialized(vault):
        raise CockpitError("vault is not initialized")

    if dry_run:
        return {"status": "dry_run", "target": "HOME.md"}

    atomic_write_text(vault, Path("HOME.md"), COCKPIT_HOME)
    return {"status": "applied", "target": "HOME.md"}


def cockpit_status(vault: Path | str) -> dict[str, object]:
    """Report cockpit file presence and freshness."""
    vault = Path(vault).absolute()
    if not is_initialized(vault):
        raise CockpitError("vault is not initialized")

    home = vault / "HOME.md"
    return {
        "cockpit_exists": home.is_file(),
        "cockpit_path": "HOME.md",
    }
