"""Obsidian-native cockpit — Markdown/Dataview review surfaces.

Generates review dashboards using canonical vault files.  Never overwrites
owner-edited files without an exact reviewed plan with expected-hash protection.

The cockpit renders two kinds of sections:
- Dataview tables over canonical folders (live in Obsidian);
- computed system-state sections (record health, feeder circuits, semantic
  index freshness) rendered at generation time from the same modules the CLI
  uses — never from hand-rolled summaries.
"""

from __future__ import annotations

from pathlib import Path

from .storage import atomic_write_text
from .vault import is_initialized


class CockpitError(RuntimeError):
    """Raised when cockpit operations fail."""


COCKPIT_HOME = """# Constellation Cockpit

> Auto-generated review dashboard. Manual edits preserved across regens.

## Candidate Queue

```dataview
TABLE file.cday AS "Staged", type AS "Type", status AS "Status"
FROM ".constellation/candidates"
SORT file.cday DESC
```

## Entity Timeline

```dataview
TABLE created_at AS "Created", sensitivity AS "Sensitivity"
FROM "entities"
SORT created_at DESC
LIMIT 20
```

## Source Evidence

```dataview
TABLE media_type AS "Format", sensitivity AS "Sensitivity"
FROM "source-items"
SORT created_at DESC
LIMIT 20
```

## Opportunities

```dataview
TABLE stage AS "Stage", probability AS "Prob", next_action AS "Next Action"
FROM "opportunities"
SORT created_at DESC
```

## Classifications

```dataview
TABLE category AS "Category", entity_id AS "Entity", confidence AS "Confidence"
FROM "classifications"
SORT created_at DESC
```

## Analyses

```dataview
TABLE framework AS "Framework", entity_id AS "Entity", confidence AS "Confidence"
FROM "analyses"
SORT created_at DESC
```

## Watchlists & Observations

```dataview
TABLE schedule AS "Schedule", sources AS "Sources"
FROM "watchlists"
SORT created_at DESC
```

## Warnings

- Degraded services: check `constellation health` output
- Stale indexes: run `constellation index` if search results seem incomplete
- Unreviewed candidates: see Candidate Queue above

_Generated by `constellation cockpit apply`_
"""


def _record_health_section(vault: Path) -> str:
    from .record_lint import lint_records

    result = lint_records(vault)
    summary = result["summary"]
    lines = [
        "## Record Health",
        "",
        f"**{summary['total']} findings** "
        f"(high: {summary.get('high', 0)}, medium: {summary.get('medium', 0)}, "
        f"low: {summary.get('low', 0)}) — {summary['total']} findings total.",
        "",
    ]
    if summary["total"] == 0:
        lines.append("0 findings. Canonical records are clean.")
    else:
        lines.append("| Severity | Check | Record | Suggested action |")
        lines.append("|---|---|---|---|")
        for finding in result["findings"][:20]:
            lines.append(
                f"| {finding['severity']} | {finding['check']} | "
                f"`{finding['record_path']}` | {finding['suggested_action']} |"
            )
    lines.append("")
    return "\n".join(lines)


def _feeder_circuits_section(vault: Path) -> str:
    from .feeders import feeder_circuit_status

    status = feeder_circuit_status(vault)
    lines = ["## Feeder Circuits", ""]
    if not status["lanes"]:
        lines.append("No feeder runs recorded yet — all lanes closed/available.")
    else:
        lines.append("| Lane | Consecutive failures | Circuit | Last status |")
        lines.append("|---|---|---|---|")
        for lane, info in status["lanes"].items():
            circuit = "OPEN" if info["circuit_open"] else "closed"
            lines.append(
                f"| {lane} | {info['consecutive_failures']} | {circuit} | "
                f"{info['last_status'] or '—'} |"
            )
    lines.append("")
    return "\n".join(lines)


def _semantic_index_section(vault: Path) -> str:
    from .semantic_index import semantic_index_status

    status = semantic_index_status(vault)
    state = status.get("status", "missing")
    lines = ["## Semantic Index", ""]
    if state == "missing":
        lines.append("Status: **missing** — run `constellation semantic build` to create one.")
    else:
        stale = "stale" if status.get("stale") else "fresh"
        lines.append(
            f"Status: **{state}** ({stale}) — "
            f"{status.get('total_entries', 0)} entries, "
            f"provider `{status.get('provider', 'unknown')}`, "
            f"generation `{status.get('generation_id', '—')}`."
        )
    lines.append("")
    return "\n".join(lines)


COCKPIT_TARGET = "COCKPIT.md"


def cockpit_plan(vault: Path | str) -> dict[str, object]:
    """Plan cockpit generation — reports what would be written.

    The cockpit writes COCKPIT.md only. HOME.md is owner-maintained and is
    never created, replaced, or overwritten by this module.
    """
    vault = Path(vault).absolute()
    if not is_initialized(vault):
        raise CockpitError("vault is not initialized")

    target = vault / COCKPIT_TARGET
    return {
        "status": "plan_ready",
        "target": COCKPIT_TARGET,
        "exists": target.is_file(),
        "action": "create" if not target.is_file() else "update",
    }


def cockpit_apply(vault: Path | str, *, dry_run: bool = False) -> dict[str, object]:
    """Generate or update the COCKPIT.md dashboard.

    Always overwrites COCKPIT.md — it is auto-generated, not user-edited.
    Owner-maintained HOME.md is never touched.
    """
    vault = Path(vault).absolute()
    if not is_initialized(vault):
        raise CockpitError("vault is not initialized")

    if dry_run:
        return {"status": "dry_run", "target": COCKPIT_TARGET}

    computed = (
        COCKPIT_HOME
        + "\n"
        + _record_health_section(vault)
        + "\n"
        + _feeder_circuits_section(vault)
        + "\n"
        + _semantic_index_section(vault)
    )
    atomic_write_text(vault, Path(COCKPIT_TARGET), computed)
    return {"status": "applied", "target": COCKPIT_TARGET}


def cockpit_status(vault: Path | str) -> dict[str, object]:
    """Report cockpit file presence and freshness."""
    vault = Path(vault).absolute()
    if not is_initialized(vault):
        raise CockpitError("vault is not initialized")

    target = vault / COCKPIT_TARGET
    return {
        "cockpit_exists": target.is_file(),
        "cockpit_path": COCKPIT_TARGET,
    }
